version: '3.8'

services:
  oidcld:
    image: ghcr.io/shibukawa/oidcld:latest
    ports:
      - "18888:18888"
    volumes:
      - ./oidcld.yaml:/app/oidcld.yaml:ro
    command: ["serve", "--config", "/app/oidcld.yaml"]
    healthcheck:
      test: ["/usr/local/bin/oidcld", "health", "--url", "http://localhost:18888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    
  # Example with environment-based configuration
  oidcld-env:
    image: ghcr.io/shibukawa/oidcld:latest
    ports:
      - "18889:18888"
    environment:
      - PORT=18888
    command: ["serve", "--port", "18888"]
    healthcheck:
      test: ["/usr/local/bin/oidcld", "health", "--url", "http://localhost:18888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    name: oidcld-network
