services:
  # OpenID Connect Identity Provider for Local Development
  oidcld:
    image: ghcr.io/shibukawa/oidcld:latest
    container_name: oidcld-demo
    ports:
      - "18888:18888"
    volumes:
      - ./oidcld-config.yaml:/app/oidcld.yaml:ro
    environment:
      - PORT=18888
      - OIDCLD_CONFIG=/app/config.yaml
    cmd: ["serve"]

  # Vue.js Sample Application (Production)
  vue-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: vue-oidc-demo-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    depends_on:
      oidcld:
        condition: service_healthy
    profiles:
      - production

volumes:
  vue_node_modules:
